In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

# Training Data (XOR Problem)
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([0, 1, 1, 0])

# Create Neural Network
model = MLPClassifier(
    hidden_layer_sizes=(2,),
    activation='logistic',
    solver='lbfgs',
    max_iter=1000,
    random_state=1
)

# Train using Backpropagation
model.fit(X, y)

# Predictions
predictions = model.predict(X)

print("Input Data:")
print(X)

print("\nActual Output:")
print(y)

print("\nPredicted Output:")
print(predictions)

# Test New Sample
test = np.array([[1, 0]])
result = model.predict(test)

print("\nPrediction for [1,0]:", result[0])

Input Data:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Actual Output:
[0 1 1 0]

Predicted Output:
[0 1 0 1]

Prediction for [1,0]: 0
